services:
  telegram-price-bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env 
    restart: unless-stopped
    command: /app/start.sh

    # analog for the key -i
    stdin_open: true
    # analog for the key -t
    tty: true 

volumes:
  data:
